User.destroy_all
Car.destroy_all
Purchase.destroy_all

u1 = User.create(name: "George")
u2 = User.create(name: "Mike")
u3 = User.create(name: "Steve")
u4 = User.create(name: "Janice")
u5 = User.create(name: "Sally")

# c1 = Car.create(model: "Toyota Camry", price: "15000", car_type:"Sedan", color:"Red", trim_level:"Base")
# c2 = Car.create(model: "Chevy Camaro", price: "10000", car_type:"Coupe", color:"Black", trim_level:"Deluxe")
# c3 = Car.create(model: "Ford F-150", price: "35000", car_type:"Truck", color:"Whitd", trim_level:"Base")
# c4 = Car.create(model: "Toyoya Sienna", price: "15000", car_type:"Minivan", color:"Red", trim_level:"Deluxe")
# c5 = Car.create(model: "Toyota Camry", price: "15000", car_type:"Sedan", color:"Black", trim_level:"Base")
# c6 = Car.create(model: "Chevy Camaro", price: "10000", car_type:"Coupe", color:"Red", trim_level:"Deluxe")
# c7 = Car.create(model: "Ford F-150", price: "35000", car_type:"Truck", color:"Red", trim_level:"Base")
# c8 = Car.create(model: "Toyoya Sienna", price: "15000", car_type:"Minivan", color:"Black", trim_level:"Deluxe")
# c9 = Car.create(model: "Toyota Camry", price: "15000", car_type:"Sedan", color:"Whited, trim_level:"Base")
# c10 = Car.create(model: "Chevy Camaro", price: "10000", car_type:"Coupe", color:"White", trim_level:"Deluxe")
# c11 = Car.create(model: "Ford F-150", price: "35000", car_type:"Truck", color:"Black", trim_level:"Deluxe")
# c12 = Car.create(model: "Toyoya Sienna", price: "15000", car_type:"Minivan", colod:"White", trim_level:"Base")

c1 = Car.create(model: "Toyota Camry", price: "10000", car_type:"Sedan", color:"White", trim_level:"Base")
c2 = Car.create(model: "Toyota Camry", price: "10000", car_type:"Sedan", color:"Black", trim_level:"Base")
c3 = Car.create(model: "Toyota Camry", price: "10000", car_type:"Sedan", color:"Red", trim_level:"Base")
c4 = Car.create(model: "Toyota Camry", price: "14000", car_type:"Sedan", color:"White", trim_level:"Deluxe")
c5 = Car.create(model: "Toyota Camry", price: "14000", car_type:"Sedan", color:"Black", trim_level:"Deluxe")
c6 = Car.create(model: "Toyota Camry", price: "14000", car_type:"Sedan", color:"Red", trim_level:"Deluxe")
c7 = Car.create(model: "Honda Civic", price: "21000", car_type:"Sedan", color:"White", trim_level:"Base")
c8 = Car.create(model: "Honda Civic", price: "21000", car_type:"Sedan", color:"Black", trim_level:"Base")
c9 = Car.create(model: "Honda Civic", price: "21000", car_type:"Sedan", color:"Red", trim_level:"Base")
c10 = Car.create(model: "Honda Civic", price: "29000", car_type:"Sedan", color:"White", trim_level:"Deluxe")
c11 = Car.create(model: "Honda Civic", price: "29000", car_type:"Sedan", color:"Black", trim_level:"Deluxe")
c12 = Car.create(model: "Honda Civic", price: "29000", car_type:"Sedan", color:"Red", trim_level:"Deluxe")
c13 = Car.create(model: "Nissan Altima", price: "33000", car_type:"Sedan", color:"White", trim_level:"Base")
c14 = Car.create(model: "Nissan Altima", price: "33000", car_type:"Sedan", color:"Black", trim_level:"Base")
c15 = Car.create(model: "Nissan Altima", price: "33000", car_type:"Sedan", color:"Red", trim_level:"Base")
c16 = Car.create(model: "Nissan Altima", price: "42000", car_type:"Sedan", color:"White", trim_level:"Deluxe")
c17 = Car.create(model: "Nissan Altima", price: "42000", car_type:"Sedan", color:"Black", trim_level:"Deluxe")
c18 = Car.create(model: "Nissan Altima", price: "42000", car_type:"Sedan", color:"Red", trim_level:"Deluxe")

c19 = Car.create(model: "Toyota Supra", price: "12000", car_type:"Coupe", color:"White", trim_level:"Base")
c20 = Car.create(model: "Toyota Supra", price: "12000", car_type:"Coupe", color:"Black", trim_level:"Base")
c21 = Car.create(model: "Toyota Supra", price: "12000", car_type:"Coupe", color:"Red", trim_level:"Base")
c22 = Car.create(model: "Toyota Supra", price: "14700", car_type:"Coupe", color:"White", trim_level:"Deluxe")
c23 = Car.create(model: "Toyota Supra", price: "14700", car_type:"Coupe", color:"Black", trim_level:"Deluxe")
c24 = Car.create(model: "Toyota Supra", price: "14700", car_type:"Coupe", color:"Red", trim_level:"Deluxe")
c25 = Car.create(model: "Honda Accord", price: "24000", car_type:"Coupe", color:"White", trim_level:"Base")
c26 = Car.create(model: "Honda Accord", price: "24000", car_type:"Coupe", color:"Black", trim_level:"Base")
c27 = Car.create(model: "Honda Accord", price: "24000", car_type:"Coupe", color:"Red", trim_level:"Base")
c28 = Car.create(model: "Honda Accord", price: "29250", car_type:"Coupe", color:"White", trim_level:"Deluxe")
c29 = Car.create(model: "Honda Accord", price: "29250", car_type:"Coupe", color:"Black", trim_level:"Deluxe")
c30 = Car.create(model: "Honda Accord", price: "29250", car_type:"Coupe", color:"Red", trim_level:"Deluxe")
c31 = Car.create(model: "Nissan 350Z", price: "37000", car_type:"Coupe", color:"White", trim_level:"Base")
c32 = Car.create(model: "Nissan 350Z", price: "37000", car_type:"Coupe", color:"Black", trim_level:"Base")
c33 = Car.create(model: "Nissan 350Z", price: "37000", car_type:"Coupe", color:"Red", trim_level:"Base")
c34 = Car.create(model: "Nissan 350Z", price: "44000", car_type:"Coupe", color:"White", trim_level:"Deluxe")
c35 = Car.create(model: "Nissan 350Z", price: "44000", car_type:"Coupe", color:"Black", trim_level:"Deluxe")
c36 = Car.create(model: "Nissan 350Z", price: "44000", car_type:"Coupe", color:"Red", trim_level:"Deluxe")

c37 = Car.create(model: "Toyota Sienna", price: "10000", car_type:"Minivan", color:"White", trim_level:"Base")
c38 = Car.create(model: "Toyota Sienna", price: "10000", car_type:"Minivan", color:"Black", trim_level:"Base")
c39 = Car.create(model: "Toyota Sienna", price: "10000", car_type:"Minivan", color:"Red", trim_level:"Base")
c40 = Car.create(model: "Toyota Sienna", price: "13222", car_type:"Minivan", color:"White", trim_level:"Deluxe")
c41 = Car.create(model: "Toyota Sienna", price: "13222", car_type:"Minivan", color:"Black", trim_level:"Deluxe")
c42 = Car.create(model: "Toyota Sienna", price: "13222", car_type:"Minivan", color:"Red", trim_level:"Deluxe")
c43 = Car.create(model: "Honda Odyssey", price: "22500", car_type:"Minivan", color:"White", trim_level:"Base")
c44 = Car.create(model: "Honda Odyssey", price: "22500", car_type:"Minivan", color:"Black", trim_level:"Base")
c45 = Car.create(model: "Honda Odyssey", price: "22500", car_type:"Minivan", color:"Red", trim_level:"Base")
c46 = Car.create(model: "Honda Odyssey", price: "29950", car_type:"Minivan", color:"White", trim_level:"Deluxe")
c47 = Car.create(model: "Honda Odyssey", price: "29950", car_type:"Minivan", color:"Black", trim_level:"Deluxe")
c48 = Car.create(model: "Honda Odyssey", price: "29950", car_type:"Minivan", color:"Red", trim_level:"Deluxe")
c49 = Car.create(model: "Nissan Quest", price: "36000", car_type:"Minivan", color:"White", trim_level:"Base")
c50 = Car.create(model: "Nissan Quest", price: "36000", car_type:"Minivan", color:"Black", trim_level:"Base")
c51 = Car.create(model: "Nissan Quest", price: "36000", car_type:"Minivan", color:"Red", trim_level:"Base")
c52 = Car.create(model: "Nissan Quest", price: "47000", car_type:"Minivan", color:"White", trim_level:"Deluxe")
c53 = Car.create(model: "Nissan Quest", price: "47000", car_type:"Minivan", color:"Black", trim_level:"Deluxe")
c54 = Car.create(model: "Nissan Quest", price: "47000", car_type:"Minivan", color:"Red", trim_level:"Deluxe")

c55 = Car.create(model: "Toyota Tacoma", price: "11000", car_type:"Truck", color:"White", trim_level:"Base")
c56 = Car.create(model: "Toyota Tacoma", price: "11000", car_type:"Truck", color:"Black", trim_level:"Base")
c57 = Car.create(model: "Toyota Tacoma", price: "11000", car_type:"Truck", color:"Red", trim_level:"Base")
c58 = Car.create(model: "Toyota Tacoma", price: "14999", car_type:"Truck", color:"White", trim_level:"Deluxe")
c59 = Car.create(model: "Toyota Tacoma", price: "14999", car_type:"Truck", color:"Black", trim_level:"Deluxe")
c60 = Car.create(model: "Toyota Tacoma", price: "14999", car_type:"Truck", color:"Red", trim_level:"Deluxe")
c61 = Car.create(model: "Honda Ridgeline", price: "22000", car_type:"Truck", color:"White", trim_level:"Base")
c62 = Car.create(model: "Honda Ridgeline", price: "22000", car_type:"Truck", color:"Black", trim_level:"Base")
c63 = Car.create(model: "Honda Ridgeline", price: "22000", car_type:"Truck", color:"Red", trim_level:"Base")
c64 = Car.create(model: "Honda Ridgeline", price: "27500", car_type:"Truck", color:"White", trim_level:"Deluxe")
c65 = Car.create(model: "Honda Ridgeline", price: "27500", car_type:"Truck", color:"Black", trim_level:"Deluxe")
c66 = Car.create(model: "Honda Ridgeline", price: "27500", car_type:"Truck", color:"Red", trim_level:"Deluxe")
c67 = Car.create(model: "Nissan Titan", price: "44000", car_type:"Truck", color:"White", trim_level:"Base")
c68 = Car.create(model: "Nissan Titan", price: "44000", car_type:"Truck", color:"Black", trim_level:"Base")
c69 = Car.create(model: "Nissan Titan", price: "44000", car_type:"Truck", color:"Red", trim_level:"Base")
c70 = Car.create(model: "Nissan Titan", price: "61000", car_type:"Truck", color:"White", trim_level:"Deluxe")
c71 = Car.create(model: "Nissan Titan", price: "61000", car_type:"Truck", color:"Black", trim_level:"Deluxe")
c72 = Car.create(model: "Nissan Titan", price: "61000", car_type:"Truck", color:"Red", trim_level:"Deluxe")